apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hazelcast-operator
  template:
    metadata:
      labels:
        name: hazelcast-operator
    spec:
      containers:
        - name: hazelcast-operator
          image: scan.connect.redhat.com/ospid-8e4976d8-5748-4bb4-818a-552eb6d3f867/hazelcast-operator:0.1.3
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
