kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: hazelcast-operator
rules:
- apiGroups:
  - hazelcast.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-hazelcast-operator
  namespace: hazelcast-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: hazelcast-operator
roleRef:
  kind: Role
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
